### ISSUE TITLE
app.js

### ISSUE THREAD

**Issue by theSimplex** [bvjones/Steami#2]
Can you guys post non-obfuscated node  part of the app?
Doing similar project, only with python backend. Got curious about node.

**Comment by rkclark** [comment]
Hey man, have a look at the server.js file in the src directory. That's where the express (node) server is created. It's a little messy, we had a very tight time limit and didn't get chance to refactor it!

**Comment by theSimplex** [comment]
Thanks, will do!
Was that a hackathon of some sort you did?

**Comment by rkclark** [comment]
We are students​ at the Makers Academy in London, a 12 week software engineering boot camp. In week 9 we get to pitch and build ideas for a web app or some kind. This was my idea! We had about 4 and and half days to do it. We were all totally new to React so it was a great learning experience :)

**Comment by rkclark** [comment]
I'll close this issue but feel free to ask anything else!
